services:
  - type: web
    name: nihss-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt && python backend/manage.py collectstatic --noinput && python backend/manage.py migrate
    startCommand: gunicorn --chdir backend nihss.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: nihss-db
          property: connectionString

databases:
  - name: nihss-db
    databaseName: nihss_db
    user: nihss_user
    plan: free
