services:
  - type: web
    name: nihss-backend
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt && python backend/manage.py collectstatic --noinput && python backend/manage.py migrate
    startCommand: gunicorn --chdir backend nihss.wsgi:application --bind 0.0.0.0:$PORT --workers 2
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: nihss-backend.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: nihss-db
          property: connectionString
      - key: GIGACHAT_CREDENTIALS
        sync: false

databases:
  - name: nihss-db
    databaseName: nihss_db
    user: nihss_user
    plan: free
